version: '3.8'
services:
  backend:
    image: taskmanager-backend:latest
    container_name: taskmanager-backend-prod
    ports:
      - "5000:80"
    volumes:
      - /var/lib/taskmanager/data:/app/Data  # Use host path
    networks:
      - app-network

  frontend:
    image: taskmanager-frontend:latest
    container_name: taskmanager-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
