version: '3.8'
services:
  backend:
    image: taskmanager-backend:latest
    container_name: taskmanager-backend-prod
    ports:
      - "5000:80"
    volumes:
      - backend_data:/app/Data  # Add this line
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: taskmanager-frontend:latest
    container_name: taskmanager-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:  # Add this section
  backend_data:
    driver: local
